# Generated by Django 5.1.5 on 2025-02-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('userAuthe', '0012_projectmembers_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='userAuthe.studentproject'),
        ),
    ]
